### ISSUE TITLE
XML rpc throws error when trying to use unoconvert with remote unoserver

### ISSUE THREAD

**Issue by mops1k** [unoconv/unoserver#122]
I'm trying to convert thru remote server (docker container with name "unoserver"), in another container i have installed unoserver package with python3 and php (trying to make a library to work with), no libreoffice. When command execute, error throwing.

Output:
```bash
# /usr/bin/unoconvert --host unoserver --port 2003 --host-location remote --convert-to pdf - - < '/app/tests/Stubs/Document.docx' > '/tmp/phpkFMHMh'
Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(converter_main())
  File "/usr/lib/python3.10/site-packages/unoserver/client.py", line 277, in converter_main
    result = client.convert(
  File "/usr/lib/python3.10/site-packages/unoserver/client.py", line 98, in convert
    result = proxy.convert(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'TypeError'>:UnoServer.serve.<locals>.convert() takes from 0 to 7 positional arguments but 8 were given">
```

Can somebody help me?

**Comment by regebro** [comment]
That sounds like a version issue, that the client isn't the same version as the server.

**Comment by mops1k** [comment]
> That sounds like a version issue, that the client isn't the same version as the server.

You was right. Now i update unoserver to 2.1 version in both containers. Now has new error:
```bash
# unoconvert --host unoserver --port 2003 --host-location remote --convert-to pdf - - < /app/tests/Stubs/Document.docx > /tmp/phpCbfFBd
Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(converter_main())
  File "/usr/lib/python3.10/site-packages/unoserver/client.py", line 277, in converter_main
    result = client.convert(
  File "/usr/lib/python3.10/site-packages/unoserver/client.py", line 98, in convert
    result = proxy.convert(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'unoserver.converter.com.sun.star.io.IOException'>:SfxBaseModel::impl_store <private:stream> failed: 0xc10(Error Area:Io Class:Write Code:16) at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.5.5.2/sfx2/source/doc/sfxbasemodel.cxx:3213 at /home/buildozer/aports/community/libreoffice/src/libreoffice-7.5.5.2/sfx2/source/doc/sfxbasemodel.cxx:1789">
```

what i am doing wrong?

**Comment by regebro** [comment]
There's no point in streaming in the infile, just pass in the infile directly. Otherwise it doesn't know what kind of file it is trying to open.

**Comment by mops1k** [comment]
> There's no point in streaming in the infile, just pass in the infile directly. Otherwise it doesn't know what kind of file it is trying to open.

Looks like unoserver-docker is outdated. I build new image with apk upgrade and pip install unoserver -U and all works fine.
Thanks for help.
