### ISSUE TITLE
unoconvert ConnectionRefusedError

### ISSUE THREAD

**Issue by SimoCanc** [unoconv/unoserver#147]
Hi all,
When executing the following command: <br>
`unoconvert abc.pptx abc.pdf`

I get the following error: <br>
`INFO:unoserver:Connecting.
Traceback (most recent call last):
  File "/usr/local/bin/unoconvert", line 8, in <module>
    sys.exit(converter_main())
  File "/usr/local/lib/python3.10/dist-packages/unoserver/client.py", line 355, in converter_main
    result = client.convert(
  File "/usr/local/lib/python3.10/dist-packages/unoserver/client.py", line 125, in convert
    info = self._connect(proxy)
  File "/usr/local/lib/python3.10/dist-packages/unoserver/client.py", line 53, in _connect
    info = proxy.info()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1178, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1291, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1321, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

<br>
I don't know if this could be due to the fact that I'm using `WSL` with `Ubuntu 22.04.05 LTS`.

**Comment by regebro** [comment]
It means it couldn't find the `unoserver`, so it's not started, or not running on a standard port.
