### ISSUE TITLE
Failing to convert docx to pdf

### ISSUE THREAD

**Issue by ccvivien** [unoconv/unoserver#15]
Hello,

I have some trouble understanding an error message. It occurs when my app tries to convert a docx file to pdf.

```python
    cmd = 'unoconvert --convert-to pdf {} {}'.format(document_name, output_name).split()

    p = subprocess.Popen(cmd, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    output, error = p.communicate()
```

I get the following:

```
INFO:unoserver:Starting unoconverter. 
INFO:unoserver:Opening /tmp/3224c812-4046-418b-b2f7-52e122fc1ab4.docx 
Traceback (most recent call last): 
File "/usr/local/bin/unoconvert", line 8, in <module> 
    sys.exit(main()) 
File "/usr/local/lib/python3.9/dist-packages/unoserver/converter.py", line 245, in main 
    result = converter.convert( 
File "/usr/local/lib/python3.9/dist-packages/unoserver/converter.py", line 153, in convert 
    document = self.desktop.loadComponentFromURL( unoserver.converter.DisposedException: ./sfx2/source/doc/sfxbasemodel.cxx:2926 
```

**Comment by regebro** [comment]
Is it a specific file? Could I in that case get a copy to test locally?
