### ISSUE TITLE
Unoserver installation on Windows

### ISSUE THREAD

**Issue by SimonAnnetts** [unoconv/unoserver#153]
Hi,

I know that Unoserver on Windows is not yet fully tested.

I'm having issues just getting it to run at all!

I've installed unoserver.exe unoconvert.exe and unocompare.exe into the main LibreOffice folder in C:\Program Files\LibreOffice\program

LibreOffice version is 24.8.3.2

I've tried installing the unoserver library files into all these locations:

C:\Program Files\LibreOffice\program\site-packages\unoserver
C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\unoserver
C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\site-packages\unoserver

I always get the following error when running unoserver.exe
```
Traceback (most recent call last):
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\site-packages\unoserver\converter.py", line 2, in <module>
    import uno
ModuleNotFoundError: No module named 'uno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\LibreOffice\program\unoserver.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\site-packages\unoserver\server.py", line 21, in <module>
    from unoserver import converter, comparer
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\site-packages\unoserver\converter.py", line 4, in <module>
    raise ImportError(
ImportError: Could not find the 'uno' library. This package must be installed with a Python installation that has a 'uno' library. This typically means you should install it with the same Python executable as your Libreoffice installation uses.
```

and a slightly different error running unoconvert.exe

```
Traceback (most recent call last):
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\LibreOffice\program\unoconvert.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\site-packages\unoserver\client.py", line 10, in <module>
    __version__ = metadata.version("unoserver")
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\importlib\metadata.py", line 569, in version
    return distribution(distribution_name).version
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\importlib\metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Program Files\LibreOffice\program\python-core-3.9.20\lib\importlib\metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: unoserver
```

Any ideas where things should be installed at to get this working properly?

Thanks in advance!

**Comment by wister** [comment]
Hi, I just wanted to add to @nepeee solution: Once you have started `server.py` in a terminal, converted some files, and then CRTL+C to exit it. You must open a new terminal to start `server.py` again, otherwise conversion will fail. This took me some time to figure out. Cheers.
