### ISSUE TITLE
unoconvert  error when convert docx to pdf

### ISSUE THREAD

**Issue by touchsky2018** [unoconv/unoserver#35]
when i ran  unoconvert , the following error happened.
how to resolve the problem, can give some help with me @regebro 

Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/unoserver/converter.py", line 248, in main
    inpath=args.infile, outpath=args.outfile, convert_to=args.convert_to
  File "/usr/lib/python3.7/site-packages/unoserver/converter.py", line 201, in convert
    document.storeToURL(export_path, output_props)
unoserver.converter.IOException: SfxBaseModel::impl_store <file:///gsyf/app/tmp/1-%E4%B8%8A%E4%BC%A0%E8%B5%84%E6%96%99-2022%E5%B9%B4%E5%BA%A6%E5%B7%A5%E4%BC%A4%E9%A2%84%E9%98%B2%E5%9F%B9%E8%AE%AD%E9%A1%B9%E7%9B%AE%E5%91%8A%E7%9F%A5%E4%B9%A6.pdf> failed: 0x11b(Error Area:Io Class:Abort Code:27)

-----------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/unoserver/converter.py", line 201, in convert
    document.storeToURL(export_path, output_props)
unoserver.converter.DisposedException: Binary URP bridge disposed during call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/unoserver/converter.py", line 248, in main
    inpath=args.infile, outpath=args.outfile, convert_to=args.convert_to
  File "/usr/lib/python3.7/site-packages/unoserver/converter.py", line 204, in convert
    document.close(True)
uno.RuntimeException: illegal object given!

**Comment by regebro** [comment]
I think this happens if the connection between the server and client breaks in the middle of the conversion.

**Comment by regebro** [comment]
No one else seems to have had this since, so I'm closing it.
