### ISSUE TITLE
RuntimeError: The input document is of an unknown document type.

### ISSUE THREAD

**Issue by nadermx** [unoconv/unoserver#4]
Currently trying to convert and html to pdf but I get this error
```
unoconvert --convert-to pdf "hra-html.html" "hra.pdf"
INFO:unoserver:Starting unoconverter.
INFO:unoserver:Opening hra-html.html
Traceback (most recent call last):
  File "/home/www/api.to/venv/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/home/www/api.to/venv/lib/python3.8/site-packages/unoserver/converter.py", line 242, in main
    result = converter.convert(
  File "/home/www/api.to/venv/lib/python3.8/site-packages/unoserver/converter.py", line 160, in convert
    import_type = get_doc_type(document)
  File "/home/www/api.to/venv/lib/python3.8/site-packages/unoserver/converter.py", line 49, in get_doc_type
    raise RuntimeError(
RuntimeError: The input document is of an unknown document type. This is probably a bug.
Please create an issue at https://github.com/unoconv/unoserver 
```

**Comment by regebro** [comment]
Can you share the HTML file?

**Comment by regebro** [comment]
I have added a fix for this, it will be in the next release.
