### ISSUE TITLE
Convert works fine in LibreOffice but unoconvert throws errors

### ISSUE THREAD

**Issue by HaoSs07** [unoconv/unoserver#40]
pi@pibooks: ~/convert/in $ unoconvert --convert-to docx /home/pi/convert/in/John\ Galsworthy\ -\ \[Sfarsit\ de\ capitol\]\ 01\ In\ asteptare\ #2.0~5.doc /home/pi/convert/out/
INFO:unoserver:Starting unoconverter.
INFO:unoserver:Opening /home/pi/convert/in/John Galsworthy - [Sfarsit de capitol] 01 In asteptare #2.0~5.doc
INFO:unoserver:Exporting to /home/pi/convert/out/
INFO:unoserver:Using MS Word 2007 XML export filter
Traceback (most recent call last):
  File "/usr/local/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/unoserver/converter.py", line 247, in main
    result = converter.convert(
  File "/usr/local/lib/python3.9/dist-packages/unoserver/converter.py", line 201, in convert
    document.storeToURL(export_path, output_props)
unoserver.converter.IOException: SfxBaseModel::impl_store <file:///home/pi/convert/out> failed: 0x11b(Error Area:Io Class:Abort Code:27) ./sfx2/source/doc/sfxbasemodel.cxx:3153 ./sfx2/source/doc/sfxbasemodel.cxx:1735

I'm doing something wrong ?

**Comment by regebro** [comment]
You selected a directory as the outputfile, that doesn't work, it needs to be a file.

A better error message there would be desirable.

**Comment by regebro** [comment]
This has been implemented
