### ISSUE TITLE
type detection failed while running unoconvert

### ISSUE THREAD

**Issue by shaheerxt** [unoconv/unoserver#45]
hi,
please check and let me know what i'm missing-

unoserver.converter.IllegalArgumentException: Unsupported URL <file:///files_new/libretest/simple.xlsx>: "**type detection failed**"

```
$ unoserver --executable /usr/bin/libreoffice
INFO:unoserver:Starting unoserver.
INFO:unoserver:Command: /usr/bin/libreoffice --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpovte7i1v --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext

$ sudo netstat -anp | grep 2002
tcp        0      0 127.0.0.1:2002          0.0.0.0:*               LISTEN      804395/soffice.bin

$ ls
simple.xlsx

$ unoconvert --convert-to pdf ./simple.xlsx s1.pdf
INFO:unoserver:Starting unoconverter.
INFO:unoserver:Opening ./simple.xlsx
Traceback (most recent call last):
  File "/usr/local/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/unoserver/converter.py", line 247, in main
    result = converter.convert(
  File "/usr/local/lib/python3.8/dist-packages/unoserver/converter.py", line 152, in convert
    document = self.desktop.loadComponentFromURL(
unoserver.converter.IllegalArgumentException: Unsupported URL <file:///files_new/libretest/simple.xlsx>: "type detection failed"
```

**Comment by notisrac** [comment]
Just ran into the same issue! All I had to do was to install `libreoffice-writer`

`sudo apt-get install libreoffice-writer`

([source](https://stackoverflow.com/a/67939473))

**Comment by shaheerxt** [comment]
yay! it did work. Thanks for the hint @notisrac !
